name: Build images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - "scripts/build.sh"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 12 * * *"

jobs:
  docker-images:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            os: ubuntu-22.04
          - arch: aarch64
            os: ubuntu-22.04-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    env:
      ARCH_BUILD_GHCR_NAMESPACE: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.arch }} image
        run: ./scripts/build.sh ${{ matrix.arch }}
